#:import Language utility_class_and_functions.Language
<KeysListBox>:
    orientation: 'vertical'
    size_hint: 0.4, 0.6
    pos_hint: {'x': 0.05 ,'y': 0.1}

    canvas.before:
        Color:
            rgba: 0.4, 0.4, 0.4, 1
        Rectangle:
            pos: self.pos
            size: self.size
        Color:
            rgba: 1, 0, 0, 1
        Line:
            width: dp(2)
            rectangle: [*self.pos, *self.size]

    ScrollView:
        do_scroll_x: False
        do_scroll_y: True
        scroll_overall: False
        bar_width: '15dp'
        GridLayout:
            id: container
            cols: 1
            size_hint_y: None
            height: self.minimum_height
            spacing: dp(20)
            padding: dp(20)


<ChangeKey>:
    MDBoxLayout:
        orientation: 'vertical'
        md_bg_color: global_variable.color_bg_interface

        MDTopAppBar:
            title: Language._("key settings")
            anchor_title: "left"
            left_action_items: [["arrow-left", lambda x: app.Back_to_settings()]] #Change screen
            font_size: "36sp"
            elevation: 2
            size_hint_y: None
            height: self.theme_cls.standard_increment # Usa l'altezza standard Material Design

        MDFloatLayout:
            orientation: 'vertical'
            MDLabel:
                id: presentation_label
                text: Language._("key settings label")
                halign: "left"
                color: 1,1,1
                font_size: "36sp"
                padding: "30sp"
                pos: dp(0), dp(300)

            KeysListBox:
                id: keyslistbox

            MDTextField:
                id: old_key_input
                max_text_length: 16
                multiline: False
                readonly: False
                size_hint: None, None
                size: dp(300), 0
                pos: presentation_label.x + 600, presentation_label.y + 200
                font_size: '30sp'
                mode: 'rectangle'
                text_color_focus: 0, 0.6, 0.6, 1
                text_color_normal: 0, 0.6, 0.6, 1
                line_color_normal: 1, 1, 1, 1

            MDTextField:
                id: new_key_input
                max_text_length: 16
                multiline: False
                readonly: False
                size_hint: None, None
                size: dp(300), 0
                pos: old_key_input.x, presentation_label.y + 0
                font_size: '30sp'
                mode: 'rectangle'
                text_color_focus: 0, 0.6, 0.6, 1
                text_color_normal: 0, 0.6, 0.6, 1
                line_color_normal: 1, 1, 1, 1

            Button:
                id: insert_old_key
                text: "Insert"
                opacity: 1
                size_hint: None, None #Percentual dimensions
                size: dp(100), dp(70) #Real dimensions
                font_size: "36sp"
                width: "200sp"
                pos: old_key_input.x + 350, old_key_input.y + 5
                on_release: root.Insert_old()

            Button:
                id: insert_new_key
                text: "Set as new"
                opacity: 1
                size_hint: None, None #Percentual dimensions
                size: dp(100), dp(70) #Real dimensions
                font_size: "36sp"
                width: "200sp"
                pos: new_key_input.x + 350, new_key_input.y + 5
                on_release: root.Insert_new()