#:import global_variable global_variable
<SettingsScreen>:
    MDBoxLayout:
        orientation:'vertical'
        md_bg_color: global_variable.color_bg_interface

        MDTopAppBar:
            title: Language._("settings name")
            anchor_title: "left"
            left_action_items: [["arrow-left", lambda x: app.Back_to_mainscreen()]]
            font_size: "36sp"
            elevation: 2

        ScrollView:
            do_scroll_x: False
            do_scroll_y: True

            MDBoxLayout:
                orientation: "vertical"
                adaptive_height: True
                spacing: "20dp"
                padding: "30dp"
                #-----------------------------------------------
                MDLabel:
                    text: Language._("settings name gen")
                    font_size: "36sp"
                    theme_text_color: "Custom"
                    text_color: global_variable.color_text_settings
                    adaptive_height: True
                    MDTextField:
                        id: key_input
                        max_text_length: 2
                        multiline: False
                        readonly: False
                        size_hint: None, None
                        size: dp(70), dp(50)
                        pos: dp(700), dp(40)
                        font_size: '30sp'
                        mode: "rectangle"
                        line_color_normal: 1,1,1,1
                        text_color_normal: 1,1,1,1
                        input_filter: 'int'
                        text: "8"
                        on_text: global_variable.genlenght = abs(int(self.text)) if self.text and self.text not in ("", "-") else 0
                #----------------------------------------------
                MDSeparator: # Linea di separazione
                    height: "3dp"
                #----------------------------------------------